"""empty message

Revision ID: 754ec3ca36b6
Revises: 16fc24443280
Create Date: 2020-06-26 18:59:44.416295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754ec3ca36b6'
down_revision = '16fc24443280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
